--------------------------------------------------------
--  File created - Sunday-December-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIREKTOR
--------------------------------------------------------

  CREATE TABLE "EMISIJA"."DIREKTOR" 
   (	"ID" NUMBER, 
	"IME" VARCHAR2(40 BYTE), 
	"PREZIME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMISIJA
--------------------------------------------------------

  CREATE TABLE "EMISIJA"."EMISIJA" 
   (	"ID" NUMBER, 
	"NAZIV" VARCHAR2(20 BYTE), 
	"OPIS" VARCHAR2(225 BYTE), 
	"TERMIN" DATE, 
	"VODITELJ_FK" NUMBER, 
	"UREDNIK_FK" NUMBER, 
	"EMITOVANA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RASPORED_EMISIJA
--------------------------------------------------------

  CREATE TABLE "EMISIJA"."RASPORED_EMISIJA" 
   (	"ID" NUMBER, 
	"DATUM" DATE, 
	"VREME" DATE, 
	"EMISIJA_FK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UREDNIK
--------------------------------------------------------

  CREATE TABLE "EMISIJA"."UREDNIK" 
   (	"ID" NUMBER, 
	"IME" VARCHAR2(40 BYTE), 
	"PREZIME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VODITELJ
--------------------------------------------------------

  CREATE TABLE "EMISIJA"."VODITELJ" 
   (	"ID" NUMBER, 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EMISIJA.DIREKTOR
SET DEFINE OFF;
REM INSERTING into EMISIJA.EMISIJA
SET DEFINE OFF;
REM INSERTING into EMISIJA.RASPORED_EMISIJA
SET DEFINE OFF;
REM INSERTING into EMISIJA.UREDNIK
SET DEFINE OFF;
REM INSERTING into EMISIJA.VODITELJ
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index VODITELJ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMISIJA"."VODITELJ_PK" ON "EMISIJA"."VODITELJ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIREKTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMISIJA"."DIREKTOR_PK" ON "EMISIJA"."DIREKTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RASPORED_EMISIJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMISIJA"."RASPORED_EMISIJA_PK" ON "EMISIJA"."RASPORED_EMISIJA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UREDNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMISIJA"."UREDNIK_PK" ON "EMISIJA"."UREDNIK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMISIJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMISIJA"."EMISIJA_PK" ON "EMISIJA"."EMISIJA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RASPORED_EMISIJA
--------------------------------------------------------

  ALTER TABLE "EMISIJA"."RASPORED_EMISIJA" ADD CONSTRAINT "RASPORED_EMISIJA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMISIJA"."RASPORED_EMISIJA" MODIFY ("EMISIJA_FK" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."RASPORED_EMISIJA" MODIFY ("VREME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."RASPORED_EMISIJA" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."RASPORED_EMISIJA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UREDNIK
--------------------------------------------------------

  ALTER TABLE "EMISIJA"."UREDNIK" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."UREDNIK" ADD CONSTRAINT "UREDNIK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMISIJA"."UREDNIK" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."UREDNIK" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."UREDNIK" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."UREDNIK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIREKTOR
--------------------------------------------------------

  ALTER TABLE "EMISIJA"."DIREKTOR" ADD CONSTRAINT "DIREKTOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMISIJA"."DIREKTOR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."DIREKTOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."DIREKTOR" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."DIREKTOR" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."DIREKTOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VODITELJ
--------------------------------------------------------

  ALTER TABLE "EMISIJA"."VODITELJ" ADD CONSTRAINT "VODITELJ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMISIJA"."VODITELJ" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."VODITELJ" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."VODITELJ" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."VODITELJ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMISIJA
--------------------------------------------------------

  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("EMITOVANA" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" ADD CONSTRAINT "EMISIJA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("UREDNIK_FK" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("VODITELJ_FK" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("TERMIN" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("OPIS" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "EMISIJA"."EMISIJA" MODIFY ("ID" NOT NULL ENABLE);
